version: '2.1'
services:

  web:
    image: nginx
    container_name: trinity-nginx
    ports:
# ---- laravel
      - "8085:8085"
    links:
      - php
      - mysql
      - redis

    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    container_name: trinity-php
    volumes_from:
      - code

  mysql:
    image: mysql:5.7.21
    container_name: trinity-mysql
    ports:
#      - "33061:3306"
      - "3306:3306"
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - ./mysql:/var/lib/mysql
      - ./mysql-entrypoint:/docker-entrypoint-initdb.d
      - ./www/service/laravel/_migration:/_migration/laravel
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    container_name: trinity-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
 
  code:
    container_name: trinity-code
    image: busybox
    volumes:
      - ./www:/var/www
      - ./php-entrypoint:/php-entrypoint